[phases.setup]
nixPkgs = ["python310"]
paths = ["/opt/venv/bin"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    "/opt/venv/bin/pip install -r FastAPI/requirements.txt"
]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "/opt/venv/bin/uvicorn app.main:app --host 0.0.0.0 --port $PORT"

