[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = ["cd FastAPI && python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "cd FastAPI && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
